### ISSUE TITLE
Xbox One controller on bluetooth didn't work as expected

### ISSUE THREAD

**Issue by waumand** [FelixKratz/moonlight-mac#1]
Hello,

first at all : you make a great job here, it's a nice idea. Hope it'll improve Moonlight for mac users, I had mouse input lag with chrome app and here it's better, less lag.

I have an Xbox One controller linked in bluetooth and it's working perfectly with the chrome app, but only the direction in joystick can work with your mac app. So there is no detection of xbox map I think. Any idea ?

Btw, I didn't succeed to have HEVC on Macbook Pro Retina late 2013 (on Iris, I have hardware HEVC normally, i try with Shadow it's ok), or iMac 27" 2013. I only got H.264 with your app.

Thank's !

**Comment by FelixKratz** [comment]
Currently there is only support for DS3/DS4 Controllers, but I plan on adding support for more controllers. You could try to install a driver for the xbox one controller that emulates a DS Controller, as the sony controllers are supported natively by macOS.

HEVC will only work if the processor supports hardware decoding, however you can use the software fallback by enabling the "Streaming Remotely"-Toggle, this will force the use of HEVC.

**Comment by jasonridesabike** [comment]
Ditto for Xbox One S controller, which is natively supported in MacOS now via bluetooth.

It actually does transmit button presses already, just the wrong ones; everything apart from the analogue sticks (which do work correctly), all buttons appear to be randomly mapped.

**Comment by FelixKratz** [comment]
Thank you for reporting, I have implemented a gamepad mapper but it is still a little buggy. I will try to make a release with this changes on the weekend.

**Comment by jasonridesabike** [comment]
No problem, I'm available to test if you need me to.

**Comment by FelixKratz** [comment]
You can download the latest release now if you wish, let me know if it works, thank you!

**Comment by jasonridesabike** [comment]
Everything appears to work apart from the dpad. Strangely, on the dpad left and up map to axis 6 and right and down map to axis 7, which isn't possible to correctly set given the current mapper.

**Comment by FelixKratz** [comment]
Yes i did notice that, there is in fact a way to add the axis of the D Pad, just leave out the Button Mapping of the Dpad and instead map the Dpad axis to UD-Axis and LR-Axis on the bottom of the mapping tool.

**Comment by FelixKratz** [comment]
I have implemented some changes, now it hopefully works. Would be great if someone could report back on the xbox controller issues.
