### ISSUE TITLE
Mouse Lag

### ISSUE THREAD

**Issue by johnblaze00** [FelixKratz/moonlight-mac#2]
Hey, 

Just tried this out on my 2017 air. The chrome client works okay so i thought i would give this a shot. While the performance seems better there is a TREMENDOUS amount of mouse lag. Like i move the mouse and the cursor follows behing REALLY slowly. 

Thank you for your work on this so far, a native client is great!

**Comment by FelixKratz** [comment]
I can reproduce this with a high DPI mouse. Maybe a problem with the mouseMoved event that spams the pipeline... I will be looking into this soon, should be a trivial fix. Thanks for reporting!

**Comment by johnblaze00** [comment]
Thanks for the reply

That makes sense. I'm using a gaming mouse. I'm pretty sure the native moonlight/limelight client had the same issue way back when.

Thanks again

-g

**Comment by johnblaze00** [comment]
This is working great now!

Thank you for the quick update and reply!

Looking forward to all the updates to this!

-g
