### ISSUE TITLE
exit current app button

### ISSUE THREAD

**Issue by johnblaze00** [FelixKratz/moonlight-mac#4]
Is it possible to get an exit current app button like the official client? 
![screen shot 2018-06-23 at 1 08 28 pm](https://user-images.githubusercontent.com/33074228/41813231-886925d8-76e6-11e8-88e4-2d99d6072f06.png)

**Comment by FelixKratz** [comment]
This seems to be a nice addition. Will be looking into this soon.

**Comment by johnblaze00** [comment]
Working on the couple games i tried.

thanks!

-g
