### ISSUE TITLE
~ key doesnt work

### ISSUE THREAD

**Issue by johnblaze00** [FelixKratz/moonlight-mac#5]
when pressing the ~ key on the keyboard, it doesnt work in moonlight

**Comment by FelixKratz** [comment]
I dont have that key on my macbook, but i will look into this when i implement a proper keyboard solution, that doesn't depend on the keyboard layout.

**Comment by FelixKratz** [comment]
I have implemented a lot of new keys in the last commit. I will release a version that contains this changes soon.

**Comment by FelixKratz** [comment]
Can you confirm that it works on your keyboard layout? I have an ISO keyboard layout, so I can not test
the US/GB layout.

**Comment by johnblaze00** [comment]
Hey buddy,

I can’t test it for at least a week. Not in town. Sorry. 

Will try asap. 

-g

**Comment by johnblaze00** [comment]
Hey,

Can confirm working now. Thanks. 

-g
